import { createApp } from 'vue';
import BootstrapVue3 from 'bootstrap-vue-3';
import VCalendar from 'v-calendar';
import VueSweetalert2 from 'vue-sweetalert2';
import VueCookies from 'vue-cookies';
import YouTube from 'vue3-youtube';
import App from './App.vue';
import router from './router';
import store from './store';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue-3/dist/bootstrap-vue-3.css';
import 'v-calendar/dist/style.css';
import 'sweetalert2/dist/sweetalert2.min.css';

const app = createApp(App);
app.use(BootstrapVue3);
app.use(store);
app.use(YouTube);
app.use(VueCookies);
app.$cookies.config('7d');
app.use(router);
app.use(VueSweetalert2);
app.use(VCalendar, {});
app.mount('#app');
